project:
  type: website

website:
  title: "Air Pollution Epidemiology"
  navbar:
    left:
      - href: publications.qmd
        text: Publications
      - href: media.qmd
        text: Media coverage
      - href: dataset.qmd
        text: Datasets
      - href: members.qmd
        text: Members

format:
  html:
    theme:
      light: yeti
      dark: darkly
    css: styles.css
    toc: true

editor: visual

